# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

linter:
  rules:
    always_put_control_body_on_new_line: false
    avoid_classes_with_only_static_members: false
    constant_identifier_names: true
    prefer_relative_imports: true

analyzer:
  exclude:
    - lib/**/**.freezed.dart
    - lib/**/**.g.dart
    - test/import_all_test.dart
  errors:
    missing_required_param: warning
    missing_return: warning
    invalid_annotation_target: ignore
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
