name: flutter_shopping_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  auto_route: ^5.0.4
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.5+1
  flutter_secure_storage: ^7.0.1
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  gap: ^2.0.0
  hooks_riverpod: ^2.0.0
  http: ^0.13.5
  import_sorter: ^4.6.0
  intl: ^0.17.0
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  logger: ^1.1.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  vibration: ^1.7.5

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  mockito: ^5.3.0
  pedantic_mono: ^1.19.2

flutter:
  uses-material-design: true

import_sorter:
  comments: false
